### ISSUE TITLE
是否可以最小化至右下角任务栏

### ISSUE THREAD

**Issue by dusdong** [MatoApps/GeneralServiceHost#1]
你好，能否让程序最小化至右下角任务栏， 这样可以防止其他人员误操作关闭了本监控程序

感谢您的开源项目~

**Comment by jevonsflash** [comment]
可以，托盘图标功能加入开发计划。

**Comment by jevonsflash** [comment]
已发布v2.1.1，添加最小化至托盘图标功能
https://github.com/MatoApps/GeneralServiceHost/releases/tag/v2.1.1
